Description: This template creates a build environment on Codebuild that automatically builds a docker image from your Github repo on push and pushes the image to ECR

Parameters:

  GithubUser:
    Type: String

  GithubRepo:
    Type: String

  CodeBuildProjectName:
    Type: String

  ImageRepoName:
    Type: String

Resources:
  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Description: 'Project'
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        PrivilegedMode: True
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: IMAGE_REPO_NAME
            Value: !Ref ImageRepo
          - Name: IMAGE_TAG
            Value: latest
      Name: !Ref CodeBuildProjectName
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: GITHUB
        Location: !Sub https://github.com/${GithubUser}/${GithubRepo}.git
        BuildSpec: !Sub |
            version: 0.2

            phases:
              pre_build:
                commands:
                  - echo Logging in to Amazon ECR...
                  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
              build:
                commands:
                  - echo Build started on `date`
                  - echo Building the Docker image...          
                  - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
                  - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
              post_build:
                commands:
                  - echo Build completed on `date`
                  - echo Pushing the Docker image...
                  - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      Triggers:
        Webhook: True


  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "codebuild.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Description: !Sub CodeBuild permissions for pushing to ECR repo ${ImageRepoName}
      Policies:
        - PolicyName: Allow-ECR-S3-Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ecr:*"
                  - "s3:*"
                  - "logs:*"
                Resource: "*"
      RoleName: !Sub CodeBuildRole-${CodeBuildProjectName}

  ImageRepo:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Ref ImageRepoName